name: my_flutter_app
description: "Streams camera feed to a server"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0          
  camera: ^0.11.1        
  path_provider: ^2.1.2  
  flutter_webrtc: ^0.13.0
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1  

flutter:
  uses-material-design: true
